name: Test Build

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master, develop ]

jobs:
  test-build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install pipenv
      run: |
        python -m pip install --upgrade pip
        pip install pipenv
    
    - name: Install dependencies
      run: |
        pipenv install
    
    - name: Test GUI components
      run: |
        pipenv run python test_gui.py
      continue-on-error: true  # GUI tests might fail in headless environment
    
    - name: Test build process
      run: |
        pipenv run pyinstaller --onefile --windowed --name=VideoConverter-test --clean --noconfirm --hidden-import=tkinter --hidden-import=tkinter.ttk --hidden-import=tkinter.filedialog --hidden-import=tkinter.messagebox convert_gui.py
    
    - name: Check if executable was created
      run: |
        if (Test-Path "dist/VideoConverter-test.exe") {
          Write-Host "✅ Executable built successfully"
          $size = (Get-Item "dist/VideoConverter-test.exe").Length / 1MB
          Write-Host "📊 File size: $([math]::Round($size, 1)) MB"
        } else {
          Write-Host "❌ Executable not found"
          exit 1
        }
      shell: powershell
    
    - name: Upload test artifacts
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: test-build-${{ github.sha }}
        path: |
          dist/VideoConverter-test.exe
        retention-days: 1
